### ISSUE TITLE
suggestions for custom tags

### ISSUE THREAD

**Issue by untuned** [LeafyLuigi/CVv6-CustomCSS#3]
I recommend you add the following other tags for donors / contributors (they are a feature in CV6 but not implemented)

List is here: https://raw.githubusercontent.com/untuned/ClearVision-v6/patch-2/src/cv/marks.scss
PR was opened on main repo to add new donors

**Comment by untuned** [comment]
try to keep the colors as well
donors are yellow
contributors are green
mods are red
jiiks can be whatever the fuck lol

**Comment by LeafyLuigi** [comment]
done. should be there if you reload and if it doesn't get deleted from credits.css
